apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-demo-app
  labels:
    app: gitops-demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitops-demo-app
  template:
    metadata:
      labels:
        app: gitops-demo-app
    spec:
      containers:
        - name: gitops-demo-app
          image: ghcr.io/anzalkhan16/gitops-demo-app:4a1115fc5047a1b605b1f7344809559642829312
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10